package com.b4rrhh.employee.working_time.infrastructure.persistence;

import com.b4rrhh.support.TestPostgresInitializer;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.test.context.ContextConfiguration;

import java.math.BigDecimal;
import java.time.LocalDate;

import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.flyway.enabled=false"
})
// Estos tests levantan su propio esquema a mano en @BeforeEach, y hasta ahora
// lo hacian contra H2. El DDL es el mismo; el motor no. Comprobar una
// restriccion de integridad en una base que no es la de produccion solo
// demuestra que H2 la respeta.
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ContextConfiguration(initializers = TestPostgresInitializer.class)
class SpringDataWorkingTimeRepositoryIntegrationTest {

    @Autowired
    private SpringDataWorkingTimeRepository repository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setUpSchema() {
        jdbcTemplate.execute("create schema if not exists employee");
        jdbcTemplate.execute("drop table if exists employee.working_time");
        jdbcTemplate.execute("""
                create table employee.working_time (
                    id bigint generated by default as identity primary key,
                    employee_id bigint not null,
                    working_time_number integer not null,
                    start_date date not null,
                    end_date date,
                    working_time_percentage numeric(5,2) not null,
                    weekly_hours numeric(6,2) not null,
                    daily_hours numeric(6,2) not null,
                    monthly_hours numeric(6,2) not null,
                    created_at timestamp not null,
                    updated_at timestamp not null,
                    constraint uk_working_time_number unique (employee_id, working_time_number),
                    constraint chk_working_time_dates check (end_date is null or start_date <= end_date)
                )
                """);
    }

    @Test
    void enforcesUniqueConstraintPerEmployeeAndWorkingTimeNumber() {
        repository.saveAndFlush(workingTimeEntity(10L, 1, LocalDate.of(2026, 1, 1), null));

        assertThrows(
                DataIntegrityViolationException.class,
                () -> repository.saveAndFlush(workingTimeEntity(10L, 1, LocalDate.of(2026, 2, 1), null))
        );
    }

    @Test
    void detectsOverlappingPeriodsUsingRepositoryQuery() {
        repository.saveAndFlush(workingTimeEntity(10L, 1, LocalDate.of(2026, 1, 1), LocalDate.of(2026, 1, 31)));

        boolean overlap = repository.existsOverlappingPeriod(
                10L,
                LocalDate.of(2026, 1, 15),
                LocalDate.of(2026, 2, 15),
                LocalDate.of(9999, 12, 31)
        );

        assertTrue(overlap);
    }

    private WorkingTimeEntity workingTimeEntity(Long employeeId, Integer workingTimeNumber, LocalDate startDate, LocalDate endDate) {
        WorkingTimeEntity entity = new WorkingTimeEntity();
        entity.setEmployeeId(employeeId);
        entity.setWorkingTimeNumber(workingTimeNumber);
        entity.setStartDate(startDate);
        entity.setEndDate(endDate);
        entity.setWorkingTimePercentage(new BigDecimal("50.00"));
        entity.setWeeklyHours(new BigDecimal("20.00"));
        entity.setDailyHours(new BigDecimal("4.00"));
        entity.setMonthlyHours(new BigDecimal("83.33"));
        return entity;
    }
}