package com.b4rrhh.employee.working_time.infrastructure.persistence;

import com.b4rrhh.support.TestPostgresInitializer;
import jakarta.persistence.EntityManager;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.test.context.ContextConfiguration;

import java.time.LocalDate;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.flyway.enabled=false"
})
// Estos tests levantan su propio esquema a mano en @BeforeEach, y hasta ahora
// lo hacian contra H2. El DDL es el mismo; el motor no. Comprobar una
// restriccion de integridad en una base que no es la de produccion solo
// demuestra que H2 la respeta.
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ContextConfiguration(initializers = TestPostgresInitializer.class)
class WorkingTimeConsistencyAdaptersIntegrationTest {

    @Autowired
    private EntityManager entityManager;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    private WorkingTimePresenceConsistencyAdapter presenceConsistencyAdapter;

    @BeforeEach
    void setUp() {
        presenceConsistencyAdapter = new WorkingTimePresenceConsistencyAdapter(entityManager);

        jdbcTemplate.execute("create schema if not exists employee");
        jdbcTemplate.execute("drop table if exists employee.presence");

        jdbcTemplate.execute("""
                create table employee.presence (
                    id bigint generated by default as identity primary key,
                    employee_id bigint not null,
                    start_date date not null,
                    end_date date
                )
                """);
    }

    @Test
    void openEndedWorkingTimeIsInsideOpenEndedPresence() {
        jdbcTemplate.update(
                "insert into employee.presence (employee_id, start_date, end_date) values (?,?,?)",
                10L,
                LocalDate.of(2020, 1, 5),
                null
        );

        boolean inside = presenceConsistencyAdapter.existsPresenceContainingPeriod(
                10L,
                LocalDate.of(2020, 1, 5),
                null
        );

        assertTrue(inside);
    }

    @Test
    void openEndedWorkingTimeIsOutsideClosedPresence() {
        jdbcTemplate.update(
                "insert into employee.presence (employee_id, start_date, end_date) values (?,?,?)",
                10L,
                LocalDate.of(2020, 1, 5),
                LocalDate.of(2020, 12, 31)
        );

        boolean outside = presenceConsistencyAdapter.existsPresenceContainingPeriod(
                10L,
                LocalDate.of(2020, 1, 5),
                null
        );

        assertFalse(outside);
    }
}