package com.b4rrhh.employee.contract.infrastructure.persistence;

import com.b4rrhh.support.DatosDePrueba;
import com.b4rrhh.support.TestSobreEsquemaReal;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;

import java.time.LocalDate;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

@TestSobreEsquemaReal
// El DDL a mano que habia aqui ya divergia del real: el subtipo de contrato
// tenia un check de longitud exacta 3 que V92 sustituyo por uno de no-vacio
// (los codigos SEPE no miden 3), y el id era 'generated by default' donde
// produccion tiene 'always'.
class SpringDataContractRepositoryIntegrationTest {

    @Autowired
    private SpringDataContractRepository repository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Test
    void enforcesUniqueConstraintByFunctionalIdentity() {
        Long empleado = DatosDePrueba.empleado(jdbcTemplate);
        repository.saveAndFlush(entity(empleado, "IND", "FT1", LocalDate.of(2026, 1, 1), null));

        assertThrows(
                DataIntegrityViolationException.class,
                () -> repository.saveAndFlush(entity(
                        empleado,
                        "TMP",
                        "PT1",
                        LocalDate.of(2026, 1, 1),
                        null
                ))
        );
    }

    @Test
    void enforcesForeignKeyConstraint() {
        assertThrows(
                DataIntegrityViolationException.class,
                () -> repository.saveAndFlush(entity(
                        999999999L,
                        "IND",
                        "FT1",
                        LocalDate.of(2026, 1, 1),
                        null
                ))
        );
    }

    @Test
    void detectsOverlapAndSupportsExcludeStartDate() {
        Long empleado = DatosDePrueba.empleado(jdbcTemplate);
        repository.saveAndFlush(entity(
                empleado,
                "IND",
                "FT1",
                LocalDate.of(2026, 1, 1),
                LocalDate.of(2026, 1, 31)
        ));

        boolean overlap = repository.existsOverlappingPeriod(
                empleado,
                LocalDate.of(2026, 1, 15),
                LocalDate.of(2026, 2, 1),
                LocalDate.of(9999, 12, 31),
                null
        );

        boolean overlapExcluded = repository.existsOverlappingPeriod(
                empleado,
                LocalDate.of(2026, 1, 15),
                LocalDate.of(2026, 2, 1),
                LocalDate.of(9999, 12, 31),
                LocalDate.of(2026, 1, 1)
        );

        boolean nonOverlap = repository.existsOverlappingPeriod(
                empleado,
                LocalDate.of(2026, 2, 1),
                LocalDate.of(2026, 2, 28),
                LocalDate.of(9999, 12, 31),
                null
        );

        assertTrue(overlap);
        assertFalse(overlapExcluded);
        assertFalse(nonOverlap);
    }

    // Un fallo por test, y no dos seguidos: en Postgres, cuando una sentencia
    // revienta dentro de una transaccion, la transaccion queda envenenada y
    // todo lo que venga detras responde "current transaction is aborted". H2
    // dejaba seguir, asi que los dos assertThrows cabian en un mismo test.
    @Test
    void rejectsContractCodeShorterThanThree() {
        assertThrows(
                DataIntegrityViolationException.class,
                () -> repository.saveAndFlush(entity(
                        DatosDePrueba.empleado(jdbcTemplate),
                        "AB",
                        "FT1",
                        LocalDate.of(2026, 1, 1),
                        null
                ))
        );
    }

    @Test
    void rejectsContractCodeLongerThanThree() {
        assertThrows(
                DataIntegrityViolationException.class,
                () -> repository.saveAndFlush(entity(
                        DatosDePrueba.empleado(jdbcTemplate),
                        "ABCD",
                        "FT1",
                        LocalDate.of(2026, 2, 1),
                        null
                ))
        );
    }

    // El subtipo ya no mide exactamente 3: V92 relajo el check porque los
    // codigos SEPE no siguen ese estandar. Lo que produccion exige hoy es que
    // no venga en blanco (chk_contract_subtype_code_nonempty).
    @Test
    void rejectsBlankContractSubtypeCode() {
        assertThrows(
                DataIntegrityViolationException.class,
                () -> repository.saveAndFlush(entity(
                        DatosDePrueba.empleado(jdbcTemplate),
                        "IND",
                        "   ",
                        LocalDate.of(2026, 1, 1),
                        null
                ))
        );
    }

    private ContractEntity entity(
            Long employeeId,
            String contractCode,
            String contractSubtypeCode,
            LocalDate startDate,
            LocalDate endDate
    ) {
        ContractEntity entity = new ContractEntity();
        entity.setEmployeeId(employeeId);
        entity.setContractCode(contractCode);
        entity.setContractSubtypeCode(contractSubtypeCode);
        entity.setStartDate(startDate);
        entity.setEndDate(endDate);
        return entity;
    }
}
