package com.b4rrhh.employee.contract.infrastructure.persistence;

import com.b4rrhh.support.TestPostgresInitializer;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.test.context.ContextConfiguration;

import java.time.LocalDate;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.flyway.enabled=false"
})
// Estos tests levantan su propio esquema a mano en @BeforeEach, y hasta ahora
// lo hacian contra H2. El DDL es el mismo; el motor no. Comprobar una
// restriccion de integridad en una base que no es la de produccion solo
// demuestra que H2 la respeta.
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ContextConfiguration(initializers = TestPostgresInitializer.class)
class SpringDataContractRepositoryIntegrationTest {

    @Autowired
    private SpringDataContractRepository repository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setUpSchema() {
        jdbcTemplate.execute("create schema if not exists employee");
        jdbcTemplate.execute("drop table if exists employee.contract");
                jdbcTemplate.execute("drop table if exists employee.employee cascade");

        jdbcTemplate.execute("""
                create table employee.employee (
                    id bigint primary key,
                    rule_system_code varchar(5) not null,
                    employee_type_code varchar(30) not null,
                    employee_number varchar(15) not null
                )
                """);

        jdbcTemplate.execute("""
                create table employee.contract (
                    id bigint generated by default as identity primary key,
                    employee_id bigint not null,
                    contract_code varchar(30) not null,
                    contract_subtype_code varchar(30) not null,
                    start_date date not null,
                    end_date date,
                    created_at timestamp not null,
                    updated_at timestamp not null,
                    constraint fk_contract_employee
                        foreign key (employee_id) references employee.employee(id),
                    constraint uk_contract_business unique (employee_id, start_date),
                                        constraint chk_contract_code_length check (char_length(contract_code) = 3),
                                        constraint chk_contract_subtype_code_length check (char_length(contract_subtype_code) = 3),
                    constraint chk_contract_dates check (end_date is null or start_date <= end_date)
                )
                """);

        jdbcTemplate.update(
                "insert into employee.employee (id, rule_system_code, employee_type_code, employee_number) values (?,?,?,?)",
                10L,
                "ESP",
                "INTERNAL",
                "EMP001"
        );
    }

    @Test
    void enforcesUniqueConstraintByFunctionalIdentity() {
        repository.saveAndFlush(entity(10L, "IND", "FT1", LocalDate.of(2026, 1, 1), null));

        assertThrows(
                DataIntegrityViolationException.class,
                () -> repository.saveAndFlush(entity(
                        10L,
                        "TMP",
                        "PT1",
                        LocalDate.of(2026, 1, 1),
                        null
                ))
        );
    }

    @Test
    void enforcesForeignKeyConstraint() {
        assertThrows(
                DataIntegrityViolationException.class,
                () -> repository.saveAndFlush(entity(
                        999L,
                        "IND",
                        "FT1",
                        LocalDate.of(2026, 1, 1),
                        null
                ))
        );
    }

    @Test
    void detectsOverlapAndSupportsExcludeStartDate() {
        repository.saveAndFlush(entity(
                10L,
                "IND",
                "FT1",
                LocalDate.of(2026, 1, 1),
                LocalDate.of(2026, 1, 31)
        ));

        boolean overlap = repository.existsOverlappingPeriod(
                10L,
                LocalDate.of(2026, 1, 15),
                LocalDate.of(2026, 2, 1),
                LocalDate.of(9999, 12, 31),
                null
        );

        boolean overlapExcluded = repository.existsOverlappingPeriod(
                10L,
                LocalDate.of(2026, 1, 15),
                LocalDate.of(2026, 2, 1),
                LocalDate.of(9999, 12, 31),
                LocalDate.of(2026, 1, 1)
        );

        boolean nonOverlap = repository.existsOverlappingPeriod(
                10L,
                LocalDate.of(2026, 2, 1),
                LocalDate.of(2026, 2, 28),
                LocalDate.of(9999, 12, 31),
                null
        );

        assertTrue(overlap);
        assertFalse(overlapExcluded);
        assertFalse(nonOverlap);
    }

    // Un fallo por test, y no dos seguidos: en Postgres, cuando una sentencia
    // revienta dentro de una transaccion, la transaccion queda envenenada y
    // todo lo que venga detras responde "current transaction is aborted". H2
    // dejaba seguir, asi que los dos assertThrows cabian en un mismo test.
    @Test
    void rejectsContractCodeShorterThanThree() {
        assertThrows(
                DataIntegrityViolationException.class,
                () -> repository.saveAndFlush(entity(
                        10L,
                        "AB",
                        "FT1",
                        LocalDate.of(2026, 1, 1),
                        null
                ))
        );
    }

    @Test
    void rejectsContractCodeLongerThanThree() {
        assertThrows(
                DataIntegrityViolationException.class,
                () -> repository.saveAndFlush(entity(
                        10L,
                        "ABCD",
                        "FT1",
                        LocalDate.of(2026, 2, 1),
                        null
                ))
        );
    }

    @Test
    void rejectsContractSubtypeCodeShorterThanThree() {
        assertThrows(
                DataIntegrityViolationException.class,
                () -> repository.saveAndFlush(entity(
                        10L,
                        "IND",
                        "AB",
                        LocalDate.of(2026, 1, 1),
                        null
                ))
        );
    }

    @Test
    void rejectsContractSubtypeCodeLongerThanThree() {
        assertThrows(
                DataIntegrityViolationException.class,
                () -> repository.saveAndFlush(entity(
                        10L,
                        "IND",
                        "ABCD",
                        LocalDate.of(2026, 2, 1),
                        null
                ))
        );
    }

    private ContractEntity entity(
            Long employeeId,
            String contractCode,
            String contractSubtypeCode,
            LocalDate startDate,
            LocalDate endDate
    ) {
        ContractEntity entity = new ContractEntity();
        entity.setEmployeeId(employeeId);
        entity.setContractCode(contractCode);
        entity.setContractSubtypeCode(contractSubtypeCode);
        entity.setStartDate(startDate);
        entity.setEndDate(endDate);
        return entity;
    }
}
