package com.b4rrhh.rulesystem.companyprofile.infrastructure.persistence;

import com.b4rrhh.support.TestPostgresInitializer;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.test.context.ContextConfiguration;

import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.flyway.enabled=false"
})
// Estos tests levantan su propio esquema a mano en @BeforeEach, y hasta ahora
// lo hacian contra H2. El DDL es el mismo; el motor no. Comprobar una
// restriccion de integridad en una base que no es la de produccion solo
// demuestra que H2 la respeta.
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ContextConfiguration(initializers = TestPostgresInitializer.class)
class SpringDataCompanyProfileRepositoryIntegrationTest {

    @Autowired
    private SpringDataCompanyProfileRepository repository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setUpSchema() {
        jdbcTemplate.execute("create schema if not exists rulesystem");
        jdbcTemplate.execute("drop table if exists rulesystem.company_profile");
        jdbcTemplate.execute("""
                create table rulesystem.company_profile (
                    id bigint generated by default as identity primary key,
                    company_rule_entity_id bigint not null,
                    legal_name varchar(200) not null,
                    tax_identifier varchar(50),
                    street varchar(300),
                    city varchar(120),
                    postal_code varchar(20),
                    region_code varchar(30),
                    country_code char(3),
                    epigrafe_at_code varchar(10),
                    created_at timestamp not null,
                    updated_at timestamp not null,
                    constraint uk_company_profile_company_rule_entity unique (company_rule_entity_id)
                )
                """);
    }

    @Test
    void enforcesUniqueConstraintPerCompanyRuleEntity() {
        repository.saveAndFlush(profileEntity(10L, "Acme Spain SA"));

        assertThrows(
                DataIntegrityViolationException.class,
                () -> repository.saveAndFlush(profileEntity(10L, "Another Legal Name"))
        );
    }

    @Test
    void findsByCompanyRuleEntityId() {
        repository.saveAndFlush(profileEntity(10L, "Acme Spain SA"));

        assertTrue(repository.findByCompanyRuleEntityId(10L).isPresent());
    }

    private CompanyProfileEntity profileEntity(Long companyRuleEntityId, String legalName) {
        CompanyProfileEntity entity = new CompanyProfileEntity();
        entity.setCompanyRuleEntityId(companyRuleEntityId);
        entity.setLegalName(legalName);
        return entity;
    }
}