package com.b4rrhh.employee.contact.infrastructure.persistence;

import com.b4rrhh.support.DatosDePrueba;
import com.b4rrhh.support.EsquemaRealInitializer;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.test.context.ContextConfiguration;

import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.flyway.enabled=false"
})
// El esquema no lo declara el test: es el de produccion, aplicado por Flyway
// una vez y clonado para este contexto. El DDL a mano que habia aqui ya no
// coincidia con el real: le faltaba la clave ajena a employee.employee (por
// eso el test podia insertar el empleado 10 sin que existiera), el id era
// 'generated by default' donde produccion tiene 'always', y created_at y
// updated_at no tenian default.
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ContextConfiguration(initializers = EsquemaRealInitializer.class)
class SpringDataContactRepositoryIntegrationTest {

    @Autowired
    private SpringDataContactRepository repository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Test
    void enforcesUniqueConstraintPerEmployeeAndContactType() {
        Long empleado = DatosDePrueba.empleado(jdbcTemplate);
        repository.saveAndFlush(contactEntity(empleado, "EMAIL", "first@example.com"));

        assertThrows(
                DataIntegrityViolationException.class,
                () -> repository.saveAndFlush(contactEntity(empleado, "EMAIL", "second@example.com"))
        );
    }

    @Test
    void allowsSameContactTypeForDifferentEmployees() {
        Long uno = DatosDePrueba.empleado(jdbcTemplate);
        Long otro = DatosDePrueba.empleado(jdbcTemplate);
        repository.saveAndFlush(contactEntity(uno, "EMAIL", "first@example.com"));
        repository.saveAndFlush(contactEntity(otro, "EMAIL", "second@example.com"));

        assertTrue(repository.findByEmployeeIdAndContactTypeCode(otro, "EMAIL").isPresent());
    }

    private ContactEntity contactEntity(Long employeeId, String contactTypeCode, String contactValue) {
        ContactEntity entity = new ContactEntity();
        entity.setEmployeeId(employeeId);
        entity.setContactTypeCode(contactTypeCode);
        entity.setContactValue(contactValue);
        return entity;
    }
}