package com.b4rrhh.employee.contact.infrastructure.persistence;

import com.b4rrhh.support.TestPostgresInitializer;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.test.context.ContextConfiguration;

import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.flyway.enabled=false"
})
// Estos tests levantan su propio esquema a mano en @BeforeEach, y hasta ahora
// lo hacian contra H2. El DDL es el mismo; el motor no. Comprobar una
// restriccion de integridad en una base que no es la de produccion solo
// demuestra que H2 la respeta.
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ContextConfiguration(initializers = TestPostgresInitializer.class)
class SpringDataContactRepositoryIntegrationTest {

    @Autowired
    private SpringDataContactRepository repository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setUpSchema() {
        jdbcTemplate.execute("create schema if not exists employee");
        jdbcTemplate.execute("drop table if exists employee.contact");
        jdbcTemplate.execute("""
                create table employee.contact (
                    id bigint generated by default as identity primary key,
                    employee_id bigint not null,
                    contact_type_code varchar(30) not null,
                    contact_value varchar(300) not null,
                    created_at timestamp not null,
                    updated_at timestamp not null,
                    constraint uk_contact_employee_type unique (employee_id, contact_type_code)
                )
                """);
    }

    @Test
    void enforcesUniqueConstraintPerEmployeeAndContactType() {
        repository.saveAndFlush(contactEntity(10L, "EMAIL", "first@example.com"));

        assertThrows(
                DataIntegrityViolationException.class,
                () -> repository.saveAndFlush(contactEntity(10L, "EMAIL", "second@example.com"))
        );
    }

    @Test
    void allowsSameContactTypeForDifferentEmployees() {
        repository.saveAndFlush(contactEntity(10L, "EMAIL", "first@example.com"));
        repository.saveAndFlush(contactEntity(11L, "EMAIL", "second@example.com"));

        assertTrue(repository.findByEmployeeIdAndContactTypeCode(11L, "EMAIL").isPresent());
    }

    private ContactEntity contactEntity(Long employeeId, String contactTypeCode, String contactValue) {
        ContactEntity entity = new ContactEntity();
        entity.setEmployeeId(employeeId);
        entity.setContactTypeCode(contactTypeCode);
        entity.setContactValue(contactValue);
        return entity;
    }
}