package com.b4rrhh.employee.identifier.infrastructure.persistence;

import com.b4rrhh.support.TestPostgresInitializer;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.test.context.ContextConfiguration;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.flyway.enabled=false"
})
// Estos tests levantan su propio esquema a mano en @BeforeEach, y hasta ahora
// lo hacian contra H2. El DDL es el mismo; el motor no. Comprobar una
// restriccion de integridad en una base que no es la de produccion solo
// demuestra que H2 la respeta.
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ContextConfiguration(initializers = TestPostgresInitializer.class)
class SpringDataIdentifierRepositoryIntegrationTest {

    @Autowired
    private SpringDataIdentifierRepository repository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setUpSchema() {
        jdbcTemplate.execute("create schema if not exists employee");
        jdbcTemplate.execute("drop table if exists employee.identifier");
        jdbcTemplate.execute("""
                create table employee.identifier (
                    id bigint generated by default as identity primary key,
                    employee_id bigint not null,
                    identifier_type_code varchar(30) not null,
                    identifier_value varchar(120) not null,
                    issuing_country_code varchar(3),
                    expiration_date date,
                    is_primary boolean not null,
                    created_at timestamp not null,
                    updated_at timestamp not null,
                    constraint uk_identifier_employee_type unique (employee_id, identifier_type_code)
                )
                """);
    }

    @Test
    void enforcesUniqueConstraintPerEmployeeAndIdentifierType() {
        repository.saveAndFlush(identifierEntity(10L, "NATIONAL_ID", "12345678A", true));

        assertThrows(
                DataIntegrityViolationException.class,
                () -> repository.saveAndFlush(identifierEntity(10L, "NATIONAL_ID", "87654321Z", false))
        );
    }

    @Test
    void allowsSameIdentifierTypeForDifferentEmployees() {
        repository.saveAndFlush(identifierEntity(10L, "NATIONAL_ID", "12345678A", true));
        repository.saveAndFlush(identifierEntity(11L, "NATIONAL_ID", "87654321Z", false));

        assertTrue(repository.findByEmployeeIdAndIdentifierTypeCode(11L, "NATIONAL_ID").isPresent());
    }

    @Test
    void supportsPrimaryLookupMethods() {
        repository.saveAndFlush(identifierEntity(10L, "NATIONAL_ID", "12345678A", true));
        repository.saveAndFlush(identifierEntity(10L, "PASSPORT", "PA123456", false));

        assertTrue(repository.existsByEmployeeIdAndIsPrimaryTrue(10L));
        assertTrue(repository.existsByEmployeeIdAndIsPrimaryTrueAndIdentifierTypeCodeNot(10L, "PASSPORT"));
        assertFalse(repository.existsByEmployeeIdAndIsPrimaryTrueAndIdentifierTypeCodeNot(10L, "NATIONAL_ID"));
    }

    private IdentifierEntity identifierEntity(Long employeeId, String identifierTypeCode, String identifierValue, boolean isPrimary) {
        IdentifierEntity entity = new IdentifierEntity();
        entity.setEmployeeId(employeeId);
        entity.setIdentifierTypeCode(identifierTypeCode);
        entity.setIdentifierValue(identifierValue);
        entity.setIssuingCountryCode("ESP");
        entity.setPrimary(isPrimary);
        return entity;
    }
}
