package com.b4rrhh.rulesystem.workcenter.infrastructure.persistence;

import com.b4rrhh.support.TestPostgresInitializer;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.test.context.ContextConfiguration;

import java.time.LocalDate;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.flyway.enabled=false"
})
// Estos tests levantan su propio esquema a mano en @BeforeEach, y hasta ahora
// lo hacian contra H2. El DDL es el mismo; el motor no. Comprobar una
// restriccion de integridad en una base que no es la de produccion solo
// demuestra que H2 la respeta.
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ContextConfiguration(initializers = TestPostgresInitializer.class)
class SpringDataWorkCenterProfileRepositoryIntegrationTest {

    @Autowired
    private SpringDataWorkCenterProfileRepository repository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setUpSchema() {
        jdbcTemplate.execute("create schema if not exists rulesystem");
        jdbcTemplate.execute("drop table if exists rulesystem.work_center_profile");
        jdbcTemplate.execute("drop table if exists rulesystem.rule_entity");
        jdbcTemplate.execute("""
                create table rulesystem.rule_entity (
                    id bigint generated by default as identity primary key,
                    rule_system_code varchar(5) not null,
                    rule_entity_type_code varchar(30) not null,
                    code varchar(30) not null,
                    name varchar(100) not null,
                    description varchar(500),
                    active boolean not null,
                    start_date date not null,
                    end_date date,
                    created_at timestamp not null,
                    updated_at timestamp not null
                )
                """);
        jdbcTemplate.execute("""
                create table rulesystem.work_center_profile (
                    id bigint generated by default as identity primary key,
                    work_center_rule_entity_id bigint not null,
                    company_code varchar(30) not null,
                    street varchar(300),
                    city varchar(120),
                    postal_code varchar(20),
                    region_code varchar(30),
                    country_code char(3),
                    created_at timestamp not null,
                    updated_at timestamp not null,
                    constraint uk_work_center_profile_rule_entity unique (work_center_rule_entity_id)
                )
                """);

        jdbcTemplate.update("""
                insert into rulesystem.rule_entity (
                    rule_system_code, rule_entity_type_code, code, name, description, active,
                    start_date, end_date, created_at, updated_at
                ) values (?, ?, ?, ?, ?, ?, ?, ?, current_timestamp, current_timestamp)
                """, "ESP", "WORK_CENTER", "MADRID_01", "Madrid 01", null, true,
                LocalDate.of(2020, 1, 1), null);
        jdbcTemplate.update("""
                insert into rulesystem.rule_entity (
                    rule_system_code, rule_entity_type_code, code, name, description, active,
                    start_date, end_date, created_at, updated_at
                ) values (?, ?, ?, ?, ?, ?, ?, ?, current_timestamp, current_timestamp)
                """, "ESP", "WORK_CENTER", "BARCELONA_01", "Barcelona 01", null, true,
                LocalDate.of(2020, 1, 1), null);
        jdbcTemplate.update("""
                insert into rulesystem.rule_entity (
                    rule_system_code, rule_entity_type_code, code, name, description, active,
                    start_date, end_date, created_at, updated_at
                ) values (?, ?, ?, ?, ?, ?, ?, ?, current_timestamp, current_timestamp)
                """, "ESP", "WORK_CENTER", "LEGACY_01", "Legacy 01", null, true,
                LocalDate.of(2010, 1, 1), LocalDate.of(2020, 12, 31));

        jdbcTemplate.update("""
                insert into rulesystem.work_center_profile (
                    work_center_rule_entity_id, company_code, created_at, updated_at
                ) values (1, 'COMP', current_timestamp, current_timestamp)
                """);
        jdbcTemplate.update("""
                insert into rulesystem.work_center_profile (
                    work_center_rule_entity_id, company_code, created_at, updated_at
                ) values (2, 'OTHER', current_timestamp, current_timestamp)
                """);
        jdbcTemplate.update("""
                insert into rulesystem.work_center_profile (
                    work_center_rule_entity_id, company_code, created_at, updated_at
                ) values (3, 'COMP', current_timestamp, current_timestamp)
                """);
    }

    @Test
    void findsApplicableWorkCentersForCompanyAndReferenceDate() {
        List<SpringDataWorkCenterProfileRepository.WorkCenterCatalogOptionRow> rows =
                repository.findWorkCentersByRuleSystemCodeAndCompanyCode(
                        "ESP",
                        "COMP",
                        LocalDate.of(2026, 4, 15),
                        null
                );

        assertEquals(1, rows.size());
        assertEquals("MADRID_01", rows.get(0).getCode());
        assertEquals("Madrid 01", rows.get(0).getName());
    }
}
