package com.b4rrhh.payroll.basesalary.infrastructure.persistence;

import com.b4rrhh.support.TestSobreBaseVacia;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;

import java.math.BigDecimal;
import java.time.LocalDate;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

@TestSobreBaseVacia
class BaseSalaryPersistenceLookupsTest {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private PayrollObjectBindingLookupAdapter bindingLookupAdapter;

    @Autowired
    private PayrollTableRowLookupAdapter tableRowLookupAdapter;

    @Autowired
    private EmployeeAgreementCategoryLookupAdapter agreementCategoryLookupAdapter;

    @BeforeEach
    void setUpSchema() {
        jdbcTemplate.execute("create schema if not exists payroll");
        jdbcTemplate.execute("create schema if not exists employee");

        jdbcTemplate.execute("""
                create table if not exists payroll.payroll_object_binding (
                    id bigint generated by default as identity primary key,
                    rule_system_code varchar(10) not null,
                    owner_type_code varchar(50) not null,
                    owner_code varchar(100) not null,
                    binding_role_code varchar(50) not null,
                    bound_object_type_code varchar(50) not null,
                    bound_object_code varchar(100) not null,
                    active boolean not null,
                    created_at timestamp,
                    updated_at timestamp
                )
                """);

        jdbcTemplate.execute("""
                create table if not exists payroll.payroll_table_row (
                    id bigint generated by default as identity primary key,
                    rule_system_code varchar(10) not null,
                    table_code varchar(100) not null,
                    search_code varchar(100) not null,
                    start_date date not null,
                    end_date date,
                    monthly_value numeric(10,2),
                    annual_value numeric(10,2),
                    daily_value numeric(10,2),
                    hourly_value numeric(10,2),
                    active boolean not null,
                    created_at timestamp,
                    updated_at timestamp
                )
                """);

        jdbcTemplate.execute("""
                create table if not exists employee.labor_classification (
                    id bigint generated by default as identity primary key,
                    employee_id bigint not null,
                    agreement_code varchar(30) not null,
                    agreement_category_code varchar(30) not null,
                    start_date date not null,
                    end_date date,
                    created_at timestamp,
                    updated_at timestamp
                )
                """);

        jdbcTemplate.execute("delete from payroll.payroll_object_binding");
        jdbcTemplate.execute("delete from payroll.payroll_table_row");
        jdbcTemplate.execute("delete from employee.labor_classification");
    }

    @Test
    void bindingLookupFiltersByActiveAndBoundObjectTypeTable() {
        jdbcTemplate.update(
                """
                insert into payroll.payroll_object_binding (
                    rule_system_code, owner_type_code, owner_code, binding_role_code,
                    bound_object_type_code, bound_object_code, active
                ) values (?, ?, ?, ?, ?, ?, ?)
                """,
                "ESP", "AGREEMENT", "A1", "BASE_SALARY_TABLE", "TABLE", "SB_A1", true
        );
        jdbcTemplate.update(
                """
                insert into payroll.payroll_object_binding (
                    rule_system_code, owner_type_code, owner_code, binding_role_code,
                    bound_object_type_code, bound_object_code, active
                ) values (?, ?, ?, ?, ?, ?, ?)
                """,
                "ESP", "AGREEMENT", "A2", "BASE_SALARY_TABLE", "TABLE", "SB_A2", false
        );
        jdbcTemplate.update(
                """
                insert into payroll.payroll_object_binding (
                    rule_system_code, owner_type_code, owner_code, binding_role_code,
                    bound_object_type_code, bound_object_code, active
                ) values (?, ?, ?, ?, ?, ?, ?)
                """,
                "ESP", "AGREEMENT", "A3", "BASE_SALARY_TABLE", "PAYROLL_CONCEPT", "SB_A3", true
        );

        assertEquals(
                "SB_A1",
                bindingLookupAdapter.resolveBoundObjectCode("ESP", "AGREEMENT", "A1", "BASE_SALARY_TABLE").orElseThrow()
        );
        assertTrue(bindingLookupAdapter.resolveBoundObjectCode("ESP", "AGREEMENT", "A2", "BASE_SALARY_TABLE").isEmpty());
        assertTrue(bindingLookupAdapter.resolveBoundObjectCode("ESP", "AGREEMENT", "A3", "BASE_SALARY_TABLE").isEmpty());
    }

    @Test
    void tableRowLookupReturnsLatestValidRowForEffectiveDate() {
        jdbcTemplate.update(
                """
                insert into payroll.payroll_table_row (
                    rule_system_code, table_code, search_code, start_date, end_date, monthly_value, active
                ) values (?, ?, ?, ?, ?, ?, ?)
                """,
                "ESP", "SB_1", "C1", LocalDate.of(2024, 1, 1), null, new BigDecimal("1200.00"), true
        );
        jdbcTemplate.update(
                """
                insert into payroll.payroll_table_row (
                    rule_system_code, table_code, search_code, start_date, end_date, monthly_value, active
                ) values (?, ?, ?, ?, ?, ?, ?)
                """,
                "ESP", "SB_1", "C1", LocalDate.of(2025, 1, 1), null, new BigDecimal("1400.00"), true
        );
        jdbcTemplate.update(
                """
                insert into payroll.payroll_table_row (
                    rule_system_code, table_code, search_code, start_date, end_date, monthly_value, active
                ) values (?, ?, ?, ?, ?, ?, ?)
                """,
                "ESP", "SB_1", "C1", LocalDate.of(2023, 1, 1), LocalDate.of(2023, 12, 31), new BigDecimal("999.00"), true
        );

        BigDecimal resolved = tableRowLookupAdapter.resolveMonthlyValue(
                "ESP",
                "SB_1",
                "C1",
                LocalDate.of(2026, 1, 15)
        ).orElseThrow();

        assertEquals(0, new BigDecimal("1400.00").compareTo(resolved));
    }

    @Test
    void agreementCategoryLookupReturnsLatestValidCategory() {
        long employeeId = 999L;

        jdbcTemplate.update(
                """
                insert into employee.labor_classification (
                    employee_id, agreement_code, agreement_category_code, start_date, end_date
                ) values (?, ?, ?, ?, ?)
                """,
                employeeId, "99002405011982", "G1", LocalDate.of(2024, 1, 1), LocalDate.of(2024, 12, 31)
        );
        jdbcTemplate.update(
                """
                insert into employee.labor_classification (
                    employee_id, agreement_code, agreement_category_code, start_date, end_date
                ) values (?, ?, ?, ?, ?)
                """,
                employeeId, "99002405011982", "G2", LocalDate.of(2025, 1, 1), null
        );

        assertEquals(
                "G2",
                agreementCategoryLookupAdapter.resolveAgreementCategoryCode(employeeId, LocalDate.of(2026, 1, 15)).orElseThrow()
        );
        assertTrue(agreementCategoryLookupAdapter.resolveAgreementCategoryCode(employeeId, LocalDate.of(2023, 1, 1)).isEmpty());
    }
}
