package com.b4rrhh.employee.cost_center.infrastructure.persistence;

import com.b4rrhh.support.TestPostgresInitializer;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.test.context.ContextConfiguration;

import java.math.BigDecimal;
import java.time.LocalDate;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.flyway.enabled=false"
})
// Estos tests levantan su propio esquema a mano en @BeforeEach, y hasta ahora
// lo hacian contra H2. El DDL es el mismo; el motor no. Comprobar una
// restriccion de integridad en una base que no es la de produccion solo
// demuestra que H2 la respeta.
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ContextConfiguration(initializers = TestPostgresInitializer.class)
class SpringDataCostCenterRepositoryIntegrationTest {

    @Autowired
    private SpringDataCostCenterRepository repository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setUpSchema() {
        jdbcTemplate.execute("create schema if not exists employee");
        jdbcTemplate.execute("drop table if exists employee.cost_center");
        jdbcTemplate.execute("drop table if exists employee.contract");
        jdbcTemplate.execute("drop table if exists employee.employee cascade");
        jdbcTemplate.execute("""
                create table employee.employee (
                    id bigint primary key,
                    rule_system_code varchar(5) not null,
                    employee_type_code varchar(30) not null,
                    employee_number varchar(15) not null
                )
                """);
        jdbcTemplate.execute("""
                create table employee.cost_center (
                    id bigint generated by default as identity primary key,
                    employee_id bigint not null,
                    cost_center_code varchar(30) not null,
                    allocation_percentage numeric(5,2) not null,
                    start_date date not null,
                    end_date date,
                    created_at timestamp not null,
                    updated_at timestamp not null,
                    constraint fk_cost_center_employee foreign key (employee_id) references employee.employee(id),
                    constraint uk_cost_center_business unique (employee_id, cost_center_code, start_date),
                    constraint chk_cost_center_allocation_percentage check (allocation_percentage > 0 and allocation_percentage <= 100),
                    constraint chk_cost_center_dates check (end_date is null or start_date <= end_date)
                )
                """);

        jdbcTemplate.update(
                "insert into employee.employee (id, rule_system_code, employee_type_code, employee_number) values (?,?,?,?)",
                10L,
                "ESP",
                "INTERNAL",
                "EMP001"
        );
    }

    @Test
    void enforcesUniqueConstraintByFunctionalIdentity() {
        repository.saveAndFlush(costCenterEntity(10L, "CC01", new BigDecimal("50"), LocalDate.of(2026, 1, 1), null));

        assertThrows(
                DataIntegrityViolationException.class,
                () -> repository.saveAndFlush(
                        costCenterEntity(10L, "CC01", new BigDecimal("70"), LocalDate.of(2026, 1, 1), null)
                )
        );
    }

    @Test
    void enforcesForeignKeyConstraint() {
        assertThrows(
                DataIntegrityViolationException.class,
                () -> repository.saveAndFlush(
                        costCenterEntity(999L, "CC01", new BigDecimal("50"), LocalDate.of(2026, 1, 1), null)
                )
        );
    }

    @Test
    void detectsOverlappingPeriodsOnlyForSameCostCenter() {
        repository.saveAndFlush(
                costCenterEntity(
                        10L,
                        "CC01",
                        new BigDecimal("50"),
                        LocalDate.of(2026, 1, 1),
                        LocalDate.of(2026, 1, 31)
                )
        );

        boolean overlapSameCode = repository.existsOverlappingPeriodByCostCenterCode(
                10L,
                "CC01",
                LocalDate.of(2026, 1, 15),
                LocalDate.of(2026, 2, 15),
                LocalDate.of(9999, 12, 31)
        );
        boolean overlapDifferentCode = repository.existsOverlappingPeriodByCostCenterCode(
                10L,
                "CC02",
                LocalDate.of(2026, 1, 15),
                LocalDate.of(2026, 2, 15),
                LocalDate.of(9999, 12, 31)
        );

        assertTrue(overlapSameCode);
        assertFalse(overlapDifferentCode);
    }

    private CostCenterEntity costCenterEntity(
            Long employeeId,
            String costCenterCode,
            BigDecimal allocationPercentage,
            LocalDate startDate,
            LocalDate endDate
    ) {
        CostCenterEntity entity = new CostCenterEntity();
        entity.setEmployeeId(employeeId);
        entity.setCostCenterCode(costCenterCode);
        entity.setAllocationPercentage(allocationPercentage);
        entity.setStartDate(startDate);
        entity.setEndDate(endDate);
        return entity;
    }
}
