package com.b4rrhh.employee.cost_center.infrastructure.persistence;

import com.b4rrhh.support.TestSobreBaseVacia;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

@TestSobreBaseVacia
class SpringDataCostCenterRepositoryWindowIntegrationTest {

    @Autowired
    private SpringDataCostCenterRepository repository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setUpSchema() {
        jdbcTemplate.execute("create schema if not exists employee");
        jdbcTemplate.execute("drop table if exists employee.cost_center");
        jdbcTemplate.execute("drop table if exists employee.contract");
        jdbcTemplate.execute("drop table if exists employee.employee cascade");
        jdbcTemplate.execute("""
                create table employee.employee (
                    id bigint primary key,
                    rule_system_code varchar(5) not null,
                    employee_type_code varchar(30) not null,
                    employee_number varchar(15) not null
                )
                """);
        jdbcTemplate.execute("""
                create table employee.cost_center (
                    id bigint generated by default as identity primary key,
                    employee_id bigint not null,
                    cost_center_code varchar(30) not null,
                    allocation_percentage numeric(5,2) not null,
                    start_date date not null,
                    end_date date,
                    created_at timestamp not null,
                    updated_at timestamp not null,
                    constraint fk_cost_center_employee foreign key (employee_id) references employee.employee(id),
                    constraint uk_cost_center_business unique (employee_id, cost_center_code, start_date),
                    constraint chk_cost_center_allocation_percentage check (allocation_percentage > 0 and allocation_percentage <= 100),
                    constraint chk_cost_center_dates check (end_date is null or start_date <= end_date)
                )
                """);

        jdbcTemplate.update(
                "insert into employee.employee (id, rule_system_code, employee_type_code, employee_number) values (?,?,?,?)",
                10L, "ESP", "INTERNAL", "EMP001"
        );
    }

    @Test
    void findActiveAtDateReturnsLinesWhosePeriodIncludesDate() {
        LocalDate start = LocalDate.of(2026, 1, 1);
        repository.saveAndFlush(entity(10L, "CC_A", new BigDecimal("60"), start, null));
        repository.saveAndFlush(entity(10L, "CC_B", new BigDecimal("40"), start, null));

        List<CostCenterEntity> active = repository.findActiveAtDate(10L, LocalDate.of(2026, 4, 1));

        assertEquals(2, active.size());
    }

    @Test
    void findActiveAtDateExcludesClosedLines() {
        LocalDate start = LocalDate.of(2026, 1, 1);
        LocalDate end = LocalDate.of(2026, 3, 31);
        repository.saveAndFlush(entity(10L, "CC_A", new BigDecimal("100"), start, end));

        List<CostCenterEntity> activeAfterClose = repository.findActiveAtDate(10L, LocalDate.of(2026, 4, 1));
        List<CostCenterEntity> activeBeforeClose = repository.findActiveAtDate(10L, LocalDate.of(2026, 3, 15));

        assertTrue(activeAfterClose.isEmpty());
        assertEquals(1, activeBeforeClose.size());
    }

    @Test
    void findByEmployeeIdAndStartDateReturnsAllLinesInWindow() {
        LocalDate start = LocalDate.of(2026, 4, 1);
        repository.saveAndFlush(entity(10L, "CC_A", new BigDecimal("60"), start, null));
        repository.saveAndFlush(entity(10L, "CC_B", new BigDecimal("40"), start, null));

        List<CostCenterEntity> window = repository.findByEmployeeIdAndStartDate(10L, start);

        assertEquals(2, window.size());
    }

    @Test
    void closeAllOpenForWindowSetsEndDateOnlyForOpenLines() {
        LocalDate windowStart = LocalDate.of(2026, 1, 1);
        LocalDate closeDate = LocalDate.of(2026, 3, 31);

        repository.saveAndFlush(entity(10L, "CC_A", new BigDecimal("60"), windowStart, null));
        repository.saveAndFlush(entity(10L, "CC_B", new BigDecimal("40"), windowStart, null));

        repository.closeAllOpenForWindow(10L, windowStart, closeDate);
        repository.flush();

        List<CostCenterEntity> after = repository.findByEmployeeIdAndStartDate(10L, windowStart);
        assertEquals(2, after.size());
        after.forEach(e -> assertEquals(closeDate, e.getEndDate()));
    }

    @Test
    void closeAllOpenForWindowDoesNotAffectAlreadyClosedLines() {
        LocalDate windowStart = LocalDate.of(2026, 1, 1);
        LocalDate alreadyClosed = LocalDate.of(2026, 2, 28);

        CostCenterEntity already = entity(10L, "CC_A", new BigDecimal("100"), windowStart, alreadyClosed);
        repository.saveAndFlush(already);

        repository.closeAllOpenForWindow(10L, windowStart, LocalDate.of(2026, 3, 31));
        repository.flush();

        List<CostCenterEntity> after = repository.findByEmployeeIdAndStartDate(10L, windowStart);
        assertEquals(alreadyClosed, after.get(0).getEndDate()); // unchanged
    }

    @Test
    void findActiveAtDateReturnsNothingBeforeWindowStart() {
        LocalDate start = LocalDate.of(2026, 4, 1);
        repository.saveAndFlush(entity(10L, "CC_A", new BigDecimal("100"), start, null));

        List<CostCenterEntity> result = repository.findActiveAtDate(10L, start.minusDays(1));

        assertTrue(result.isEmpty());
    }

    private CostCenterEntity entity(
            Long employeeId,
            String costCenterCode,
            BigDecimal allocationPercentage,
            LocalDate startDate,
            LocalDate endDate
    ) {
        CostCenterEntity e = new CostCenterEntity();
        e.setEmployeeId(employeeId);
        e.setCostCenterCode(costCenterCode);
        e.setAllocationPercentage(allocationPercentage);
        e.setStartDate(startDate);
        e.setEndDate(endDate);
        return e;
    }
}
