package com.b4rrhh.rulesystem.infrastructure.persistence;

import com.b4rrhh.support.TestPostgresInitializer;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.test.context.ContextConfiguration;

import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.flyway.enabled=false"
})
// Estos tests levantan su propio esquema a mano en @BeforeEach, y hasta ahora
// lo hacian contra H2. El DDL es el mismo; el motor no. Comprobar una
// restriccion de integridad en una base que no es la de produccion solo
// demuestra que H2 la respeta.
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ContextConfiguration(initializers = TestPostgresInitializer.class)
class SpringDataRuleSystemRepositoryIntegrationTest {

    @Autowired
    private SpringDataRuleSystemRepository repository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setUpSchema() {
        jdbcTemplate.execute("create schema if not exists rulesystem");
        jdbcTemplate.execute("drop table if exists rulesystem.rule_system");
        jdbcTemplate.execute("""
                create table rulesystem.rule_system (
                    id bigint generated by default as identity primary key,
                    code varchar(5) not null,
                    name varchar(100) not null,
                    country_code char(3) not null,
                    active boolean not null default true,
                    created_at timestamp not null,
                    updated_at timestamp not null,
                    constraint uk_rule_system_code unique (code)
                )
                """);
    }

    @Test
    void createSetsCreatedAtAndUpdatedAt() {
        RuleSystemEntity entity = new RuleSystemEntity();
        entity.setCode("ESP");
        entity.setName("Sistema de Reglas Espana");
        entity.setCountryCode("ESP");
        entity.setActive(true);

        RuleSystemEntity saved = repository.saveAndFlush(entity);

        assertNotNull(saved.getCreatedAt());
        assertNotNull(saved.getUpdatedAt());
        assertTrue(!saved.getUpdatedAt().isBefore(saved.getCreatedAt()));
    }

    @Test
    void updatePreservesCreatedAtRefreshesUpdatedAtAndMutatesBusinessFields() throws InterruptedException {
        RuleSystemEntity entity = new RuleSystemEntity();
        entity.setCode("ESP");
        entity.setName("Sistema de Reglas Espana");
        entity.setCountryCode("ESP");
        entity.setActive(true);

        RuleSystemEntity created = repository.saveAndFlush(entity);
        LocalDateTime createdAt = created.getCreatedAt();
        LocalDateTime updatedAtBeforeUpdate = created.getUpdatedAt();

        Thread.sleep(5L);

        RuleSystemEntity managed = repository.findByCode("ESP").orElseThrow();
        managed.setName("Sistema de Reglas Espana Actualizado");
        managed.setCountryCode("FRA");
        managed.setActive(false);

        RuleSystemEntity updated = repository.saveAndFlush(managed);

        assertEquals(createdAt, updated.getCreatedAt());
        assertTrue(updated.getUpdatedAt().isAfter(updatedAtBeforeUpdate));
        assertEquals("Sistema de Reglas Espana Actualizado", updated.getName());
        assertEquals("FRA", updated.getCountryCode());
        assertEquals(false, updated.isActive());
    }
}
