package com.b4rrhh.employee.labor_classification.infrastructure.persistence;

import com.b4rrhh.support.TestPostgresInitializer;
import jakarta.persistence.EntityManager;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.test.context.ContextConfiguration;

import java.time.LocalDate;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.flyway.enabled=false"
})
// Estos tests levantan su propio esquema a mano en @BeforeEach, y hasta ahora
// lo hacian contra H2. El DDL es el mismo; el motor no. Comprobar una
// restriccion de integridad en una base que no es la de produccion solo
// demuestra que H2 la respeta.
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ContextConfiguration(initializers = TestPostgresInitializer.class)
class LaborClassificationConsistencyAdaptersIntegrationTest {

    @Autowired
    private EntityManager entityManager;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    private LaborClassificationPresenceConsistencyAdapter presenceConsistencyAdapter;
    private AgreementCategoryRelationLookupAdapter relationLookupAdapter;

    @BeforeEach
    void setUp() {
        presenceConsistencyAdapter = new LaborClassificationPresenceConsistencyAdapter(entityManager);
        relationLookupAdapter = new AgreementCategoryRelationLookupAdapter(entityManager);

        jdbcTemplate.execute("create schema if not exists employee");
        jdbcTemplate.execute("create schema if not exists rulesystem");

        jdbcTemplate.execute("drop table if exists rulesystem.agreement_category_relation");
        jdbcTemplate.execute("drop table if exists rulesystem.rule_entity");
        jdbcTemplate.execute("drop table if exists rulesystem.rule_entity_type");
        jdbcTemplate.execute("drop table if exists rulesystem.rule_system");
        jdbcTemplate.execute("drop table if exists employee.presence");

        jdbcTemplate.execute("""
                create table employee.presence (
                    id bigint generated by default as identity primary key,
                    employee_id bigint not null,
                    start_date date not null,
                    end_date date
                )
                """);

        jdbcTemplate.execute("""
                create table rulesystem.rule_system (
                    id bigint primary key,
                    code varchar(5) not null,
                    name varchar(100),
                    country_code char(3),
                    active boolean not null
                )
                """);

        jdbcTemplate.execute("""
                create table rulesystem.rule_entity_type (
                    code varchar(30) primary key,
                    name varchar(100),
                    active boolean not null
                )
                """);

        jdbcTemplate.execute("""
                create table rulesystem.rule_entity (
                    id bigint primary key,
                    rule_system_code varchar(5) not null,
                    rule_entity_type_code varchar(30) not null,
                    code varchar(30) not null,
                    active boolean not null,
                    start_date date not null,
                    end_date date
                )
                """);

        jdbcTemplate.execute("""
                create table rulesystem.agreement_category_relation (
                    id bigint generated by default as identity primary key,
                    rule_system_id bigint not null,
                    agreement_rule_entity_id bigint not null,
                    category_rule_entity_id bigint not null,
                    start_date date not null,
                    end_date date,
                    is_active boolean not null
                )
                """);
    }

    @Test
    void presenceContainmentQueryIsCorrect() {
        jdbcTemplate.update(
                "insert into employee.presence (employee_id, start_date, end_date) values (?,?,?)",
                10L,
                LocalDate.of(2026, 1, 1),
                LocalDate.of(2026, 1, 31)
        );
        jdbcTemplate.update(
                "insert into employee.presence (employee_id, start_date, end_date) values (?,?,?)",
                10L,
                LocalDate.of(2026, 2, 10),
                null
        );

        boolean inside = presenceConsistencyAdapter.existsPresenceContainingPeriod(
                10L,
                LocalDate.of(2026, 1, 10),
                LocalDate.of(2026, 1, 20)
        );
        boolean outside = presenceConsistencyAdapter.existsPresenceContainingPeriod(
                10L,
                LocalDate.of(2026, 1, 25),
                LocalDate.of(2026, 2, 12)
        );

        assertTrue(inside);
        assertFalse(outside);
        assertEquals(2, presenceConsistencyAdapter.findPresencePeriodsByEmployeeIdOrderByStartDate(10L).size());
    }

    @Test
    void agreementCategoryRelationLookupIsCorrect() {
        jdbcTemplate.update(
                "insert into rulesystem.rule_system (id, code, name, country_code, active) values (?,?,?,?,?)",
                1L,
                "ESP",
                "Spain",
                "ESP",
                true
        );
        jdbcTemplate.update(
                "insert into rulesystem.rule_entity_type (code, name, active) values (?,?,?)",
                "AGREEMENT",
                "Agreement",
                true
        );
        jdbcTemplate.update(
                "insert into rulesystem.rule_entity_type (code, name, active) values (?,?,?)",
                "AGREEMENT_CATEGORY",
                "Agreement Category",
                true
        );

        jdbcTemplate.update(
                """
                insert into rulesystem.rule_entity (
                    id, rule_system_code, rule_entity_type_code, code, active, start_date, end_date
                ) values (?,?,?,?,?,?,?)
                """,
                100L,
                "ESP",
                "AGREEMENT",
                "AGR_OFFICE",
                true,
                LocalDate.of(1900, 1, 1),
                null
        );
        jdbcTemplate.update(
                """
                insert into rulesystem.rule_entity (
                    id, rule_system_code, rule_entity_type_code, code, active, start_date, end_date
                ) values (?,?,?,?,?,?,?)
                """,
                200L,
                "ESP",
                "AGREEMENT_CATEGORY",
                "CAT_ADMIN",
                true,
                LocalDate.of(1900, 1, 1),
                null
        );

        jdbcTemplate.update(
                """
                insert into rulesystem.agreement_category_relation (
                    rule_system_id, agreement_rule_entity_id, category_rule_entity_id, start_date, end_date, is_active
                ) values (?,?,?,?,?,?)
                """,
                1L,
                100L,
                200L,
                LocalDate.of(1900, 1, 1),
                null,
                true
        );

        boolean validRelation = relationLookupAdapter.existsActiveRelation(
                "ESP",
                "AGR_OFFICE",
                "CAT_ADMIN",
                LocalDate.of(2026, 1, 1)
        );
        boolean invalidRelation = relationLookupAdapter.existsActiveRelation(
                "ESP",
                "AGR_OFFICE",
                "CAT_TECH_1",
                LocalDate.of(2026, 1, 1)
        );

        assertTrue(validRelation);
        assertFalse(invalidRelation);
    }

    @Test
    void agreementCategoryRelationLookupHandlesNullReferenceDateWithoutSqlGrammarError() {
        seedAgreementCategoryRelationData();

        Boolean validRelation = assertDoesNotThrow(() -> relationLookupAdapter.existsActiveRelation(
                "ESP",
                "AGR_OFFICE",
                "CAT_ADMIN",
                null
        ));
        Boolean invalidRelation = assertDoesNotThrow(() -> relationLookupAdapter.existsActiveRelation(
                "ESP",
                "AGR_OFFICE",
                "CAT_TECH_1",
                null
        ));

        assertTrue(validRelation);
        assertFalse(invalidRelation);
    }

    private void seedAgreementCategoryRelationData() {
        jdbcTemplate.update(
                "insert into rulesystem.rule_system (id, code, name, country_code, active) values (?,?,?,?,?)",
                1L,
                "ESP",
                "Spain",
                "ESP",
                true
        );
        jdbcTemplate.update(
                "insert into rulesystem.rule_entity_type (code, name, active) values (?,?,?)",
                "AGREEMENT",
                "Agreement",
                true
        );
        jdbcTemplate.update(
                "insert into rulesystem.rule_entity_type (code, name, active) values (?,?,?)",
                "AGREEMENT_CATEGORY",
                "Agreement Category",
                true
        );

        jdbcTemplate.update(
                """
                insert into rulesystem.rule_entity (
                    id, rule_system_code, rule_entity_type_code, code, active, start_date, end_date
                ) values (?,?,?,?,?,?,?)
                """,
                100L,
                "ESP",
                "AGREEMENT",
                "AGR_OFFICE",
                true,
                LocalDate.of(1900, 1, 1),
                null
        );
        jdbcTemplate.update(
                """
                insert into rulesystem.rule_entity (
                    id, rule_system_code, rule_entity_type_code, code, active, start_date, end_date
                ) values (?,?,?,?,?,?,?)
                """,
                200L,
                "ESP",
                "AGREEMENT_CATEGORY",
                "CAT_ADMIN",
                true,
                LocalDate.of(1900, 1, 1),
                null
        );

        jdbcTemplate.update(
                """
                insert into rulesystem.agreement_category_relation (
                    rule_system_id, agreement_rule_entity_id, category_rule_entity_id, start_date, end_date, is_active
                ) values (?,?,?,?,?,?)
                """,
                1L,
                100L,
                200L,
                LocalDate.of(1900, 1, 1),
                null,
                true
        );
    }
}
