package com.b4rrhh.employee.labor_classification.infrastructure.persistence;

import com.b4rrhh.support.TestSobreBaseVacia;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;

import java.time.LocalDate;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

@TestSobreBaseVacia
class SpringDataLaborClassificationRepositoryIntegrationTest {

    @Autowired
    private SpringDataLaborClassificationRepository repository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setUpSchema() {
        jdbcTemplate.execute("create schema if not exists employee");
        jdbcTemplate.execute("drop table if exists employee.labor_classification");
        jdbcTemplate.execute("drop table if exists employee.contract");
        jdbcTemplate.execute("drop table if exists employee.employee cascade");

        jdbcTemplate.execute("""
                create table employee.employee (
                    id bigint primary key,
                    rule_system_code varchar(5) not null,
                    employee_type_code varchar(30) not null,
                    employee_number varchar(15) not null
                )
                """);

        jdbcTemplate.execute("""
                create table employee.labor_classification (
                    id bigint generated by default as identity primary key,
                    employee_id bigint not null,
                    agreement_code varchar(30) not null,
                    agreement_category_code varchar(30) not null,
                    start_date date not null,
                    end_date date,
                    created_at timestamp not null,
                    updated_at timestamp not null,
                    constraint fk_labor_classification_employee
                        foreign key (employee_id) references employee.employee(id),
                    constraint uk_labor_classification_business unique (employee_id, start_date),
                    constraint chk_labor_classification_dates check (end_date is null or start_date <= end_date)
                )
                """);

        jdbcTemplate.update(
                "insert into employee.employee (id, rule_system_code, employee_type_code, employee_number) values (?,?,?,?)",
                10L,
                "ESP",
                "INTERNAL",
                "EMP001"
        );
    }

    @Test
    void enforcesUniqueConstraintByFunctionalIdentity() {
        repository.saveAndFlush(entity(10L, "AGR_OFFICE", "CAT_ADMIN", LocalDate.of(2026, 1, 1), null));

        assertThrows(
                DataIntegrityViolationException.class,
                () -> repository.saveAndFlush(entity(
                        10L,
                        "AGR_TECH",
                        "CAT_TECH_1",
                        LocalDate.of(2026, 1, 1),
                        null
                ))
        );
    }

    @Test
    void enforcesForeignKeyConstraint() {
        assertThrows(
                DataIntegrityViolationException.class,
                () -> repository.saveAndFlush(entity(
                        999L,
                        "AGR_OFFICE",
                        "CAT_ADMIN",
                        LocalDate.of(2026, 1, 1),
                        null
                ))
        );
    }

    @Test
    void detectsOverlapAndSupportsExcludeStartDate() {
        repository.saveAndFlush(entity(
                10L,
                "AGR_OFFICE",
                "CAT_ADMIN",
                LocalDate.of(2026, 1, 1),
                LocalDate.of(2026, 1, 31)
        ));

        boolean overlap = repository.existsOverlappingPeriod(
                10L,
                LocalDate.of(2026, 1, 15),
                LocalDate.of(2026, 2, 1),
                LocalDate.of(9999, 12, 31),
                null
        );

        boolean overlapExcluded = repository.existsOverlappingPeriod(
                10L,
                LocalDate.of(2026, 1, 15),
                LocalDate.of(2026, 2, 1),
                LocalDate.of(9999, 12, 31),
                LocalDate.of(2026, 1, 1)
        );

        boolean nonOverlap = repository.existsOverlappingPeriod(
                10L,
                LocalDate.of(2026, 2, 1),
                LocalDate.of(2026, 2, 28),
                LocalDate.of(9999, 12, 31),
                null
        );

        assertTrue(overlap);
        assertFalse(overlapExcluded);
        assertFalse(nonOverlap);
    }

    private LaborClassificationEntity entity(
            Long employeeId,
            String agreementCode,
            String agreementCategoryCode,
            LocalDate startDate,
            LocalDate endDate
    ) {
        LaborClassificationEntity entity = new LaborClassificationEntity();
        entity.setEmployeeId(employeeId);
        entity.setAgreementCode(agreementCode);
        entity.setAgreementCategoryCode(agreementCategoryCode);
        entity.setStartDate(startDate);
        entity.setEndDate(endDate);
        return entity;
    }
}
