-- backend#158, paso 3 del camino 5 (workspace#20, ADR-077, ADR-078 §3): COUNTRY sube a INT.
--
-- Un pais es el mismo en ESP, FRA y PRT, y la V16 lo sembraba tres veces, una por reglamentacion:
-- diez paises, nombre en ingles y traduccion al castellano (V114). Aqui las tres
-- copias se quedan en una fila en INT (rulesystem.raise_rule_entity_type, V167, que falla si no son
-- identicas), y el catalogo pasa a ser el entero: los 249 codigos de ISO 3166-1, que es la semilla
-- que el camino 4 (workspace#19) necesita para el pais de la direccion.
--
-- Fuente: iso-codes 4.18.0 (Debian, https://salsa.debian.org/iso-codes-team/iso-codes),
-- data/iso_3166-1.json para el codigo alfa-3 y el nombre, e iso_3166-1/es.po para el castellano.
-- Licencia LGPL-2.1-or-later; los datos se reproducen tal cual, sin retocar ninguna traduccion
-- (tambien la tilde de «Costa de Marfíl», que es de la fuente). El nombre de la fila es el de
-- iso-codes en ingles y el castellano va en rule_entity_translation (es-ES), como estaban los
-- diez: los diez coinciden letra a letra con la fuente en los dos idiomas, y por eso no se tocan.
--
-- Codigo alfa-3 y no alfa-2 porque es el que ya guardan employee.address.country_code y
-- employee.identifier.issuing_country_code.

select rulesystem.raise_rule_entity_type('COUNTRY', 'INT');

create temp table iso_3166_1 (code varchar(3) primary key, name varchar(100) not null, name_es varchar(100) not null)
    on commit drop;

insert into iso_3166_1 (code, name, name_es) values
    ('ABW', 'Aruba', 'Aruba'),
    ('AFG', 'Afghanistan', 'Afganistán'),
    ('AGO', 'Angola', 'Angola'),
    ('AIA', 'Anguilla', 'Anguila'),
    ('ALA', 'Åland Islands', 'Islas Äland'),
    ('ALB', 'Albania', 'Albania'),
    ('AND', 'Andorra', 'Andorra'),
    ('ARE', 'United Arab Emirates', 'Emiratos Árabes Unidos'),
    ('ARG', 'Argentina', 'Argentina'),
    ('ARM', 'Armenia', 'Armenia'),
    ('ASM', 'American Samoa', 'Samoa Estadounidense'),
    ('ATA', 'Antarctica', 'Antártida'),
    ('ATF', 'French Southern Territories', 'Territorios Franceses del Sur'),
    ('ATG', 'Antigua and Barbuda', 'Antigua y Barbuda'),
    ('AUS', 'Australia', 'Australia'),
    ('AUT', 'Austria', 'Austria'),
    ('AZE', 'Azerbaijan', 'Azerbaiyán'),
    ('BDI', 'Burundi', 'Burundi'),
    ('BEL', 'Belgium', 'Bélgica'),
    ('BEN', 'Benin', 'Benín'),
    ('BES', 'Bonaire, Sint Eustatius and Saba', 'Islas BES (Caribe Neerlandés)'),
    ('BFA', 'Burkina Faso', 'Burquina Faso'),
    ('BGD', 'Bangladesh', 'Bangladés'),
    ('BGR', 'Bulgaria', 'Bulgaria'),
    ('BHR', 'Bahrain', 'Baréin'),
    ('BHS', 'Bahamas', 'Bahamas'),
    ('BIH', 'Bosnia and Herzegovina', 'Bosnia y Herzegovina'),
    ('BLM', 'Saint Barthélemy', 'San Bartolomé'),
    ('BLR', 'Belarus', 'Bielorrusia'),
    ('BLZ', 'Belize', 'Belice'),
    ('BMU', 'Bermuda', 'Islas Bermudas'),
    ('BOL', 'Bolivia, Plurinational State of', 'Bolivia, Estado plurinacional de'),
    ('BRA', 'Brazil', 'Brasil'),
    ('BRB', 'Barbados', 'Barbados'),
    ('BRN', 'Brunei Darussalam', 'Brunei Darussalam'),
    ('BTN', 'Bhutan', 'Bután'),
    ('BVT', 'Bouvet Island', 'Isla Bouvet'),
    ('BWA', 'Botswana', 'Botsuana'),
    ('CAF', 'Central African Republic', 'República Centroafricana'),
    ('CAN', 'Canada', 'Canadá'),
    ('CCK', 'Cocos (Keeling) Islands', 'Islas Cocos (Keeling)'),
    ('CHE', 'Switzerland', 'Suiza'),
    ('CHL', 'Chile', 'Chile'),
    ('CHN', 'China', 'China'),
    ('CIV', 'Côte d''Ivoire', 'Costa de Marfíl'),
    ('CMR', 'Cameroon', 'Camerún'),
    ('COD', 'Congo, The Democratic Republic of the', 'Congo, República Democrática del'),
    ('COG', 'Congo', 'Congo'),
    ('COK', 'Cook Islands', 'Islas Cook'),
    ('COL', 'Colombia', 'Colombia'),
    ('COM', 'Comoros', 'Comores, Islas'),
    ('CPV', 'Cabo Verde', 'Cabo Verde'),
    ('CRI', 'Costa Rica', 'Costa Rica'),
    ('CUB', 'Cuba', 'Cuba'),
    ('CUW', 'Curaçao', 'Curazao'),
    ('CXR', 'Christmas Island', 'Isla de Navidad'),
    ('CYM', 'Cayman Islands', 'Islas Caimán'),
    ('CYP', 'Cyprus', 'Chipre'),
    ('CZE', 'Czechia', 'Chequia'),
    ('DEU', 'Germany', 'Alemania'),
    ('DJI', 'Djibouti', 'Yibuti'),
    ('DMA', 'Dominica', 'Dominica'),
    ('DNK', 'Denmark', 'Dinamarca'),
    ('DOM', 'Dominican Republic', 'República Dominicana'),
    ('DZA', 'Algeria', 'Algeria'),
    ('ECU', 'Ecuador', 'Ecuador'),
    ('EGY', 'Egypt', 'Egipto'),
    ('ERI', 'Eritrea', 'Eritrea'),
    ('ESH', 'Western Sahara', 'Sahara Occidental'),
    ('ESP', 'Spain', 'España'),
    ('EST', 'Estonia', 'Estonia'),
    ('ETH', 'Ethiopia', 'Etiopía'),
    ('FIN', 'Finland', 'Finlandia'),
    ('FJI', 'Fiji', 'Fiyi'),
    ('FLK', 'Falkland Islands (Malvinas)', 'Islas Falkland (Malvinas)'),
    ('FRA', 'France', 'Francia'),
    ('FRO', 'Faroe Islands', 'Islas Feroe'),
    ('FSM', 'Micronesia, Federated States of', 'Micronesia, Estados Federados de'),
    ('GAB', 'Gabon', 'Gabón'),
    ('GBR', 'United Kingdom', 'Reino Unido'),
    ('GEO', 'Georgia', 'Georgia'),
    ('GGY', 'Guernsey', 'Guernsey'),
    ('GHA', 'Ghana', 'Ghana'),
    ('GIB', 'Gibraltar', 'Gibraltar'),
    ('GIN', 'Guinea', 'Guinea'),
    ('GLP', 'Guadeloupe', 'Guadalupe'),
    ('GMB', 'Gambia', 'Gambia'),
    ('GNB', 'Guinea-Bissau', 'Guinea-Bisáu'),
    ('GNQ', 'Equatorial Guinea', 'Guinea Ecuatorial'),
    ('GRC', 'Greece', 'Grecia'),
    ('GRD', 'Grenada', 'Granada'),
    ('GRL', 'Greenland', 'Groenlandia'),
    ('GTM', 'Guatemala', 'Guatemala'),
    ('GUF', 'French Guiana', 'Guayana Francesa'),
    ('GUM', 'Guam', 'Guam'),
    ('GUY', 'Guyana', 'Guyana'),
    ('HKG', 'Hong Kong', 'Hong Kong'),
    ('HMD', 'Heard Island and McDonald Islands', 'Islas Heard y McDonald'),
    ('HND', 'Honduras', 'Honduras'),
    ('HRV', 'Croatia', 'Croacia'),
    ('HTI', 'Haiti', 'Haití'),
    ('HUN', 'Hungary', 'Hungría'),
    ('IDN', 'Indonesia', 'Indonesia'),
    ('IMN', 'Isle of Man', 'Isla de Man'),
    ('IND', 'India', 'India'),
    ('IOT', 'British Indian Ocean Territory', 'Territorio Británico del Océano Índico'),
    ('IRL', 'Ireland', 'Irlanda'),
    ('IRN', 'Iran, Islamic Republic of', 'Irán, República islámica de'),
    ('IRQ', 'Iraq', 'Irak'),
    ('ISL', 'Iceland', 'Islandia'),
    ('ISR', 'Israel', 'Israel'),
    ('ITA', 'Italy', 'Italia'),
    ('JAM', 'Jamaica', 'Jamaica'),
    ('JEY', 'Jersey', 'Jersey'),
    ('JOR', 'Jordan', 'Jordania'),
    ('JPN', 'Japan', 'Japón'),
    ('KAZ', 'Kazakhstan', 'Kazajistán'),
    ('KEN', 'Kenya', 'Kenia'),
    ('KGZ', 'Kyrgyzstan', 'Kirguistán'),
    ('KHM', 'Cambodia', 'Camboya'),
    ('KIR', 'Kiribati', 'Kiribati'),
    ('KNA', 'Saint Kitts and Nevis', 'San Cristóbal y Nieves'),
    ('KOR', 'Korea, Republic of', 'Corea, República de'),
    ('KWT', 'Kuwait', 'Kuwait'),
    ('LAO', 'Lao People''s Democratic Republic', 'República Democrática Popular de Lao'),
    ('LBN', 'Lebanon', 'Líbano'),
    ('LBR', 'Liberia', 'Liberia'),
    ('LBY', 'Libya', 'Libia'),
    ('LCA', 'Saint Lucia', 'Santa Lucía'),
    ('LIE', 'Liechtenstein', 'Liechtenstein'),
    ('LKA', 'Sri Lanka', 'Sri Lanka'),
    ('LSO', 'Lesotho', 'Lesoto'),
    ('LTU', 'Lithuania', 'Lituania'),
    ('LUX', 'Luxembourg', 'Luxemburgo'),
    ('LVA', 'Latvia', 'Letonia'),
    ('MAC', 'Macao', 'Macao'),
    ('MAF', 'Saint Martin (French part)', 'San Martín (zona francesa)'),
    ('MAR', 'Morocco', 'Marruecos'),
    ('MCO', 'Monaco', 'Mónaco'),
    ('MDA', 'Moldova, Republic of', 'Moldavia, República de'),
    ('MDG', 'Madagascar', 'Madagascar'),
    ('MDV', 'Maldives', 'Islas Maldivas'),
    ('MEX', 'Mexico', 'México'),
    ('MHL', 'Marshall Islands', 'Islas Marshall'),
    ('MKD', 'North Macedonia', 'Macedonia del Norte'),
    ('MLI', 'Mali', 'Malí'),
    ('MLT', 'Malta', 'Malta'),
    ('MMR', 'Myanmar', 'Birmania'),
    ('MNE', 'Montenegro', 'Montenegro'),
    ('MNG', 'Mongolia', 'Mongolia'),
    ('MNP', 'Northern Mariana Islands', 'Islas Marianas del Norte'),
    ('MOZ', 'Mozambique', 'Mozambique'),
    ('MRT', 'Mauritania', 'Mauritania'),
    ('MSR', 'Montserrat', 'Montserrat'),
    ('MTQ', 'Martinique', 'Martinica'),
    ('MUS', 'Mauritius', 'Mauricio'),
    ('MWI', 'Malawi', 'Malaui'),
    ('MYS', 'Malaysia', 'Malasia'),
    ('MYT', 'Mayotte', 'Mayotte'),
    ('NAM', 'Namibia', 'Namibia'),
    ('NCL', 'New Caledonia', 'Nueva Caledonia'),
    ('NER', 'Niger', 'Niger'),
    ('NFK', 'Norfolk Island', 'Isla Norfolk'),
    ('NGA', 'Nigeria', 'Nigeria'),
    ('NIC', 'Nicaragua', 'Nicaragua'),
    ('NIU', 'Niue', 'Niue'),
    ('NLD', 'Netherlands', 'Países Bajos'),
    ('NOR', 'Norway', 'Noruega'),
    ('NPL', 'Nepal', 'Nepal'),
    ('NRU', 'Nauru', 'Nauru'),
    ('NZL', 'New Zealand', 'Nueva Zelanda'),
    ('OMN', 'Oman', 'Omán'),
    ('PAK', 'Pakistan', 'Pakistán'),
    ('PAN', 'Panama', 'Panamá'),
    ('PCN', 'Pitcairn', 'Pitcairn'),
    ('PER', 'Peru', 'Perú'),
    ('PHL', 'Philippines', 'Filipinas'),
    ('PLW', 'Palau', 'Palaos'),
    ('PNG', 'Papua New Guinea', 'Papúa Nueva Guinea'),
    ('POL', 'Poland', 'Polonia'),
    ('PRI', 'Puerto Rico', 'Puerto Rico'),
    ('PRK', 'Korea, Democratic People''s Republic of', 'Corea, República Democrática Popular de'),
    ('PRT', 'Portugal', 'Portugal'),
    ('PRY', 'Paraguay', 'Paraguay'),
    ('PSE', 'Palestine, State of', 'Palestina, Estado de'),
    ('PYF', 'French Polynesia', 'Polinesia Francesa'),
    ('QAT', 'Qatar', 'Catar'),
    ('REU', 'Réunion', 'Reunión'),
    ('ROU', 'Romania', 'Rumanía'),
    ('RUS', 'Russian Federation', 'Federación Rusa'),
    ('RWA', 'Rwanda', 'Ruanda'),
    ('SAU', 'Saudi Arabia', 'Arabia Saudí'),
    ('SDN', 'Sudan', 'Sudán'),
    ('SEN', 'Senegal', 'Senegal'),
    ('SGP', 'Singapore', 'Singapur'),
    ('SGS', 'South Georgia and the South Sandwich Islands', 'Islas Georgias del Sur y Sándwich del Sur'),
    ('SHN', 'Saint Helena, Ascension and Tristan da Cunha', 'Santa Elena, Ascensión y Tristán de Acuña'),
    ('SJM', 'Svalbard and Jan Mayen', 'Svalbard y Jan Mayen'),
    ('SLB', 'Solomon Islands', 'Islas Salomón'),
    ('SLE', 'Sierra Leone', 'Sierra Leona'),
    ('SLV', 'El Salvador', 'El Salvador'),
    ('SMR', 'San Marino', 'San Marino'),
    ('SOM', 'Somalia', 'Somalia'),
    ('SPM', 'Saint Pierre and Miquelon', 'San Pedro y Miquelon'),
    ('SRB', 'Serbia', 'Serbia'),
    ('SSD', 'South Sudan', 'Sudán del Sur'),
    ('STP', 'Sao Tome and Principe', 'Santo Tomé y Príncipe'),
    ('SUR', 'Suriname', 'Surinám'),
    ('SVK', 'Slovakia', 'Eslovaquia'),
    ('SVN', 'Slovenia', 'Eslovenia'),
    ('SWE', 'Sweden', 'Suecia'),
    ('SWZ', 'Eswatini', 'Esuatini'),
    ('SXM', 'Sint Maarten (Dutch part)', 'Isla de San Martín (zona holandsea)'),
    ('SYC', 'Seychelles', 'Seychelles'),
    ('SYR', 'Syrian Arab Republic', 'República árabe de Siria'),
    ('TCA', 'Turks and Caicos Islands', 'Islas Turcas y Caicos'),
    ('TCD', 'Chad', 'Chad'),
    ('TGO', 'Togo', 'Togo'),
    ('THA', 'Thailand', 'Tailandia'),
    ('TJK', 'Tajikistan', 'Tayikistán'),
    ('TKL', 'Tokelau', 'Tokelau'),
    ('TKM', 'Turkmenistan', 'Turkmenistán'),
    ('TLS', 'Timor-Leste', 'Timor Oriental'),
    ('TON', 'Tonga', 'Tonga'),
    ('TTO', 'Trinidad and Tobago', 'Trinidad y Tobago'),
    ('TUN', 'Tunisia', 'Tunez'),
    ('TUR', 'Türkiye', 'Turquía'),
    ('TUV', 'Tuvalu', 'Tuvalu'),
    ('TWN', 'Taiwan, Province of China', 'Taiwán, Provincia de China'),
    ('TZA', 'Tanzania, United Republic of', 'Tanzania, República unida de'),
    ('UGA', 'Uganda', 'Uganda'),
    ('UKR', 'Ukraine', 'Ucrania'),
    ('UMI', 'United States Minor Outlying Islands', 'Islas Ultramarinas Menores de Estados Unidos'),
    ('URY', 'Uruguay', 'Uruguay'),
    ('USA', 'United States', 'Estados Unidos'),
    ('UZB', 'Uzbekistan', 'Uzbekistán'),
    ('VAT', 'Holy See (Vatican City State)', 'Santa Sede (Ciudad Estado del Vaticano)'),
    ('VCT', 'Saint Vincent and the Grenadines', 'San Vicente y las Granadinas'),
    ('VEN', 'Venezuela, Bolivarian Republic of', 'Venezuela, República Bolivariana de'),
    ('VGB', 'Virgin Islands, British', 'Islas Vírgenes, Británicas'),
    ('VIR', 'Virgin Islands, U.S.', 'Islas Vírgenes, de EEUU'),
    ('VNM', 'Viet Nam', 'Vietnam'),
    ('VUT', 'Vanuatu', 'Vanuatu'),
    ('WLF', 'Wallis and Futuna', 'Wallis y Futuna'),
    ('WSM', 'Samoa', 'Samoa'),
    ('YEM', 'Yemen', 'Yemen'),
    ('ZAF', 'South Africa', 'Sudáfrica'),
    ('ZMB', 'Zambia', 'Zambia'),
    ('ZWE', 'Zimbabwe', 'Zimbabue')
;

-- Los diez que ya estaban, iguales a la fuente: si no lo fueran, el catalogo tendria dos verdades.
do $$
declare
    differing text;
begin
    select string_agg(format('%s: %s / %s frente a %s / %s', re.code, re.name, tr.name, iso.name, iso.name_es), '; ')
      into differing
      from rulesystem.rule_entity re
      join iso_3166_1 iso on iso.code = re.code
      left join rulesystem.rule_entity_translation tr on tr.rule_entity_id = re.id and tr.language_code = 'es-ES'
     where re.layer_code = 'INT' and re.rule_entity_type_code = 'COUNTRY'
       and (re.name <> iso.name or tr.name is distinct from iso.name_es);
    if differing is not null then
        raise exception 'Los paises sembrados no son los de iso-codes: %', differing using errcode = '23514';
    end if;
end;
$$;

insert into rulesystem.rule_entity (layer_code, rule_entity_type_code, code, name, description, active, start_date)
select 'INT', 'COUNTRY', iso.code, iso.name, 'Country catalog based on ISO 3166-1 alpha-3', true, date '1900-01-01'
  from iso_3166_1 iso
 where not exists (select 1 from rulesystem.rule_entity re
                    where re.layer_code = 'INT' and re.rule_entity_type_code = 'COUNTRY' and re.code = iso.code);

insert into rulesystem.rule_entity_translation (rule_entity_id, language_code, name, description)
select re.id, 'es-ES', iso.name_es, 'Catálogo de países según ISO 3166-1 alfa-3'
  from iso_3166_1 iso
  join rulesystem.rule_entity re on re.layer_code = 'INT' and re.rule_entity_type_code = 'COUNTRY' and re.code = iso.code
 where not exists (select 1 from rulesystem.rule_entity_translation tr
                    where tr.rule_entity_id = re.id and tr.language_code = 'es-ES');
