package com.b4rrhh.employee.journey.infrastructure.persistence;

import com.b4rrhh.support.TestPostgresInitializer;
import com.b4rrhh.employee.journey.application.port.JourneyContractReadPort;
import com.b4rrhh.employee.journey.application.port.JourneyContractRecord;
import com.b4rrhh.employee.journey.application.port.JourneyCostCenterReadPort;
import com.b4rrhh.employee.journey.application.port.JourneyCostCenterRecord;
import com.b4rrhh.employee.journey.application.port.JourneyLaborClassificationReadPort;
import com.b4rrhh.employee.journey.application.port.JourneyLaborClassificationRecord;
import com.b4rrhh.employee.journey.application.port.JourneyPresenceReadPort;
import com.b4rrhh.employee.journey.application.port.JourneyPresenceRecord;
import com.b4rrhh.employee.journey.application.port.JourneyWorkCenterReadPort;
import com.b4rrhh.employee.journey.application.port.JourneyWorkCenterRecord;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.test.context.ContextConfiguration;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.flyway.enabled=false"
})
@Import({
        JourneyPresenceReadAdapter.class,
        JourneyContractReadAdapter.class,
        JourneyLaborClassificationReadAdapter.class,
        JourneyWorkCenterReadAdapter.class,
        JourneyCostCenterReadAdapter.class,
        EmployeeJourneyLookupAdapter.class
})
// Estos tests levantan su propio esquema a mano en @BeforeEach, y hasta ahora
// lo hacian contra H2. El DDL es el mismo; el motor no. Comprobar una
// restriccion de integridad en una base que no es la de produccion solo
// demuestra que H2 la respeta.
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ContextConfiguration(initializers = TestPostgresInitializer.class)
class JourneyReadPersistenceAdapterIntegrationTest {

    @Autowired
    private JourneyPresenceReadPort journeyPresenceReadPort;

    @Autowired
    private JourneyContractReadPort journeyContractReadPort;

    @Autowired
    private JourneyLaborClassificationReadPort journeyLaborClassificationReadPort;

    @Autowired
    private JourneyWorkCenterReadPort journeyWorkCenterReadPort;

    @Autowired
    private JourneyCostCenterReadPort journeyCostCenterReadPort;

    @Autowired
    private EmployeeJourneyLookupAdapter employeeJourneyLookupAdapter;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setUpSchema() {
        jdbcTemplate.execute("create schema if not exists employee");
        jdbcTemplate.execute("drop table if exists employee.cost_center");
        jdbcTemplate.execute("drop table if exists employee.work_center");
        jdbcTemplate.execute("drop table if exists employee.labor_classification");
        jdbcTemplate.execute("drop table if exists employee.contract");
        jdbcTemplate.execute("drop table if exists employee.presence");
        jdbcTemplate.execute("drop table if exists employee.employee");

        jdbcTemplate.execute("""
                create table employee.employee (
                    id bigint primary key,
                    rule_system_code varchar(5) not null,
                    employee_type_code varchar(30) not null,
                    employee_number varchar(15) not null,
                    first_name varchar(100) not null,
                    last_name_1 varchar(100) not null,
                    last_name_2 varchar(100),
                    preferred_name varchar(300)
                )
                """);

        jdbcTemplate.execute("""
                create table employee.presence (
                    id bigint generated by default as identity primary key,
                    employee_id bigint not null,
                    presence_number integer not null,
                    company_code varchar(4) not null,
                    entry_reason_code varchar(30) not null,
                    exit_reason_code varchar(30),
                    start_date date not null,
                    end_date date
                )
                """);

        jdbcTemplate.execute("""
                create table employee.contract (
                    id bigint generated by default as identity primary key,
                    employee_id bigint not null,
                    contract_code varchar(30) not null,
                    contract_subtype_code varchar(30) not null,
                    start_date date not null,
                    end_date date
                )
                """);

        jdbcTemplate.execute("""
                create table employee.labor_classification (
                    id bigint generated by default as identity primary key,
                    employee_id bigint not null,
                    agreement_code varchar(30) not null,
                    agreement_category_code varchar(30) not null,
                    start_date date not null,
                    end_date date
                )
                """);

        jdbcTemplate.execute("""
                create table employee.work_center (
                    id bigint generated by default as identity primary key,
                    employee_id bigint not null,
                    work_center_assignment_number integer not null,
                    work_center_code varchar(30) not null,
                    start_date date not null,
                    end_date date
                )
                """);

        jdbcTemplate.execute("""
                create table employee.cost_center (
                    id bigint generated by default as identity primary key,
                    employee_id bigint not null,
                    cost_center_code varchar(30) not null,
                    allocation_percentage numeric(5,2) not null,
                    start_date date not null,
                    end_date date
                )
                """);

        jdbcTemplate.update(
                "insert into employee.employee (id, rule_system_code, employee_type_code, employee_number, first_name, last_name_1, last_name_2, preferred_name) values (?, ?, ?, ?, ?, ?, ?, ?)",
                10L,
                "ESP",
                "INTERNAL",
                "EMP001",
                "LIDIA",
                "MORALES",
                null,
                "Lidia Morales"
        );
    }

    @Test
    void readQueriesReturnOrderedRecordsByStartDateForAllTracks() {
        insertPresence(10L, 2, "C002", LocalDate.of(2026, 2, 1), null);
        insertPresence(10L, 1, "C001", LocalDate.of(2026, 1, 1), LocalDate.of(2026, 1, 31));

        insertContract(10L, "TMP", "PT1", LocalDate.of(2026, 2, 1), null);
        insertContract(10L, "IND", "FT1", LocalDate.of(2026, 1, 1), LocalDate.of(2026, 1, 31));

        insertLaborClassification(10L, "AGR_B", "CAT_B", LocalDate.of(2026, 2, 1), null);
        insertLaborClassification(10L, "AGR_A", "CAT_A", LocalDate.of(2026, 1, 1), LocalDate.of(2026, 1, 31));

        insertWorkCenter(10L, 2, "BCN", LocalDate.of(2026, 2, 1), null);
        insertWorkCenter(10L, 1, "MAD", LocalDate.of(2026, 1, 1), LocalDate.of(2026, 1, 31));

        insertCostCenter(10L, "CC20", new BigDecimal("40.00"), LocalDate.of(2026, 2, 1), null);
        insertCostCenter(10L, "CC10", new BigDecimal("60.00"), LocalDate.of(2026, 1, 1), LocalDate.of(2026, 1, 31));

        List<JourneyPresenceRecord> presences = journeyPresenceReadPort.findByEmployeeIdOrderByStartDate(10L);
        List<JourneyContractRecord> contracts = journeyContractReadPort.findByEmployeeIdOrderByStartDate(10L);
        List<JourneyLaborClassificationRecord> laborClassifications = journeyLaborClassificationReadPort.findByEmployeeIdOrderByStartDate(10L);
        List<JourneyWorkCenterRecord> workCenters = journeyWorkCenterReadPort.findByEmployeeIdOrderByStartDate(10L);
        List<JourneyCostCenterRecord> costCenters = journeyCostCenterReadPort.findByEmployeeIdOrderByStartDate(10L);

        assertEquals(LocalDate.of(2026, 1, 1), presences.get(0).startDate());
        assertEquals(LocalDate.of(2026, 1, 1), contracts.get(0).startDate());
        assertEquals(LocalDate.of(2026, 1, 1), laborClassifications.get(0).startDate());
        assertEquals(LocalDate.of(2026, 1, 1), workCenters.get(0).startDate());
        assertEquals(LocalDate.of(2026, 1, 1), costCenters.get(0).startDate());
    }

    @Test
    void costCenterQueryReturnsMultipleItemsForSameEmployee() {
        insertCostCenter(10L, "CC10", new BigDecimal("50.00"), LocalDate.of(2026, 1, 1), null);
        insertCostCenter(10L, "CC20", new BigDecimal("50.00"), LocalDate.of(2026, 1, 1), null);

        List<JourneyCostCenterRecord> costCenters = journeyCostCenterReadPort.findByEmployeeIdOrderByStartDate(10L);

        assertEquals(2, costCenters.size());
        assertEquals("CC10", costCenters.get(0).costCenterCode());
        assertEquals("CC20", costCenters.get(1).costCenterCode());
    }

    @Test
    void employeeLookupResolvesBusinessKeyAndDisplayName() {
        var employee = employeeJourneyLookupAdapter.findByBusinessKey("ESP", "INTERNAL", "EMP001").orElseThrow();

        assertEquals(10L, employee.employeeId());
        assertEquals("ESP", employee.ruleSystemCode());
        assertEquals("INTERNAL", employee.employeeTypeCode());
        assertEquals("EMP001", employee.employeeNumber());
        assertEquals("Lidia Morales", employee.displayName());
    }

    private void insertPresence(
            Long employeeId,
            Integer presenceNumber,
            String companyCode,
            LocalDate startDate,
            LocalDate endDate
    ) {
        jdbcTemplate.update(
                "insert into employee.presence (employee_id, presence_number, company_code, entry_reason_code, exit_reason_code, start_date, end_date) values (?, ?, ?, ?, ?, ?, ?)",
                employeeId,
                presenceNumber,
                companyCode,
                "ENTRY",
                null,
                startDate,
                endDate
        );
    }

    private void insertContract(
            Long employeeId,
            String contractCode,
            String contractSubtypeCode,
            LocalDate startDate,
            LocalDate endDate
    ) {
        jdbcTemplate.update(
                "insert into employee.contract (employee_id, contract_code, contract_subtype_code, start_date, end_date) values (?, ?, ?, ?, ?)",
                employeeId,
                contractCode,
                contractSubtypeCode,
                startDate,
                endDate
        );
    }

    private void insertLaborClassification(
            Long employeeId,
            String agreementCode,
            String agreementCategoryCode,
            LocalDate startDate,
            LocalDate endDate
    ) {
        jdbcTemplate.update(
                "insert into employee.labor_classification (employee_id, agreement_code, agreement_category_code, start_date, end_date) values (?, ?, ?, ?, ?)",
                employeeId,
                agreementCode,
                agreementCategoryCode,
                startDate,
                endDate
        );
    }

    private void insertWorkCenter(
            Long employeeId,
            Integer assignmentNumber,
            String workCenterCode,
            LocalDate startDate,
            LocalDate endDate
    ) {
        jdbcTemplate.update(
                "insert into employee.work_center (employee_id, work_center_assignment_number, work_center_code, start_date, end_date) values (?, ?, ?, ?, ?)",
                employeeId,
                assignmentNumber,
                workCenterCode,
                startDate,
                endDate
        );
    }

    private void insertCostCenter(
            Long employeeId,
            String costCenterCode,
            BigDecimal allocationPercentage,
            LocalDate startDate,
            LocalDate endDate
    ) {
        jdbcTemplate.update(
                "insert into employee.cost_center (employee_id, cost_center_code, allocation_percentage, start_date, end_date) values (?, ?, ?, ?, ?)",
                employeeId,
                costCenterCode,
                allocationPercentage,
                startDate,
                endDate
        );
    }
}
