package com.b4rrhh.support;

import org.flywaydb.core.Flyway;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * El esquema de produccion, aplicado una sola vez y listo para clonar.
 *
 * La primera vez que alguien lo pide, se crea una base, se le pasan TODAS las
 * migraciones reales de Flyway y se deja ahi quieta. Nadie escribe en ella:
 * solo sirve de plantilla.
 *
 * Por que plantilla y no aplicar las migraciones en cada contexto de test:
 * aplicarlas cuesta unos 3 segundos, y hay del orden de veinte contextos.
 * Postgres sabe crear una base copiando otra (CREATE DATABASE ... TEMPLATE),
 * que a nivel de disco es copiar ficheros: unos 80 milisegundos. Mismo esquema,
 * mismas semillas, cuarenta veces mas rapido.
 *
 * Lo que gana el que escribe el test es no tener que declarar el esquema. Antes
 * cada test se creaba sus tablas a mano, y esas tablas habian ido divergiendo de
 * las de verdad: en employee.contact faltaba la clave ajena a employee.employee,
 * el id era 'generated by default' donde produccion tiene 'always', y no habia
 * defaults en created_at/updated_at. Un test que pasa contra un esquema que no
 * existe en ninguna parte no demuestra gran cosa.
 */
public final class EsquemaReal {

    /** Nombre fijo: se crea una vez por JVM y no la comparte nadie mas. */
    private static final String PLANTILLA = "plantilla_esquema_real";

    private static boolean preparada;

    private EsquemaReal() {
    }

    public static synchronized String plantilla() {
        if (!preparada) {
            construir();
            preparada = true;
        }
        return PLANTILLA;
    }

    private static void construir() {
        enAdmin("drop database if exists " + PLANTILLA);
        enAdmin("create database " + PLANTILLA);

        Flyway.configure()
                .dataSource(
                        TestPostgres.jdbcUrl(PLANTILLA),
                        TestPostgres.username(),
                        TestPostgres.password())
                .locations("classpath:db/migration")
                .load()
                .migrate();

        // Postgres no clona una base que tenga sesiones abiertas. Flyway cierra
        // las suyas al terminar, pero el backend puede tardar unos milisegundos
        // en morirse del todo. Se cortan aqui, una vez; despues de esto nadie
        // se vuelve a conectar a la plantilla.
        enAdmin("select pg_terminate_backend(pid) from pg_stat_activity"
                + " where datname = '" + PLANTILLA + "' and pid <> pg_backend_pid()");
    }

    private static void enAdmin(String sentencia) {
        String urlAdmin = TestPostgres.jdbcUrl(TestPostgres.defaultDatabase());
        try (Connection conexion = DriverManager.getConnection(
                     urlAdmin, TestPostgres.username(), TestPostgres.password());
             Statement statement = conexion.createStatement()) {
            statement.execute(sentencia);
        } catch (SQLException e) {
            throw new IllegalStateException("No se pudo preparar la plantilla del esquema real: " + sentencia, e);
        }
    }
}
